export const collectionNames = [
  "Silk",
  "Cotton",
  "Banarasi",
  "Kanjivaram",
  "Chanderi",
  "Linen",
  "Bridal",
  "Festive",
  "Everyday",
];
export const defaults = {
  shipping: 14900,
  freeShipping: 500000,
  taxPercent: 0,
  cod: false,
  mode: "demo",
  deliveryMin: 4,
  deliveryMax: 8,
  phone: "[Phone]",
  email: "[Email]",
  whatsapp: "[WhatsApp]",
  address: "[Store Address]",
  banner: "A little tradition. A lifetime of grace.",
  bannerImage: "/images/hero.jpg",
};
const rows = [
  [
    "gulabi-banarasi",
    "Gulabi Banarasi Silk",
    "Silk",
    "Festive",
    "Banarasi",
    "Silk,Banarasi,Festive",
    "Rose",
    685000,
    8,
    "saree-pink-silk",
    1,
  ],
  [
    "emerald-kanjivaram",
    "Emerald Kanjivaram Silk",
    "Silk",
    "Wedding",
    "Kanjivaram",
    "Silk,Kanjivaram,Bridal",
    "Emerald",
    1295000,
    5,
    "saree-emerald",
    1,
  ],
  [
    "ivory-chanderi",
    "Ivory Chanderi Grace",
    "Silk cotton",
    "Everyday",
    "Chanderi",
    "Chanderi,Everyday",
    "Ivory",
    395000,
    12,
    "saree-ivory",
    1,
  ],
  [
    "maroon-bridal",
    "Blue & Maroon Bridal Heirloom",
    "Silk",
    "Wedding",
    "Banarasi",
    "Bridal,Silk,Banarasi",
    "Blue",
    1895000,
    3,
    "saree-blue-orange",
    1,
  ],
  [
    "indigo-cotton",
    "Checkered Cotton Daydream",
    "Cotton",
    "Everyday",
    "Plain weave",
    "Cotton,Everyday",
    "Multicolor",
    245000,
    9,
    "saree-checkered",
    0,
  ],
  [
    "golden-festive",
    "Golden Green Festive Silk",
    "Silk",
    "Festive",
    "Jacquard",
    "Silk,Festive",
    "Gold",
    795000,
    7,
    "saree-green-gold",
    0,
  ],
  [
    "rose-linen",
    "Rose Linen Whisper",
    "Linen",
    "Everyday",
    "Plain weave",
    "Linen,Everyday",
    "Rose",
    325000,
    6,
    "saree-rose-blue",
    0,
  ],
  [
    "ivory-cotton",
    "Lavender Cotton Morning",
    "Cotton",
    "Everyday",
    "Plain weave",
    "Cotton,Everyday",
    "Lavender",
    195000,
    14,
    "saree-lavender",
    0,
  ],
  [
    "emerald-banarasi",
    "Sea Green Banarasi Bloom",
    "Silk",
    "Festive",
    "Banarasi",
    "Banarasi,Festive,Silk",
    "Green",
    895000,
    2,
    "saree-sea-green",
    0,
  ],
  [
    "maroon-kanjivaram",
    "Teal Kanjivaram Vow",
    "Silk",
    "Wedding",
    "Kanjivaram",
    "Kanjivaram,Bridal,Silk",
    "Teal",
    1595000,
    4,
    "saree-blue-maroon",
    0,
  ],
  [
    "gold-chanderi",
    "Golden Chanderi Light",
    "Silk cotton",
    "Festive",
    "Chanderi",
    "Chanderi,Festive",
    "Yellow",
    445000,
    0,
    "saree-yellow",
    0,
  ],
  [
    "blue-linen",
    "Teal & Lavender Linen Reverie",
    "Linen",
    "Everyday",
    "Plain weave",
    "Linen,Everyday",
    "Teal",
    365000,
    10,
    "saree-teal-purple",
    0,
  ],
];
export const samples = rows.map((r, i) => ({
  id: `p${i + 1}`,
  slug: r[0],
  name: r[1],
  fabric: r[2],
  occasion: r[3],
  weave: r[4],
  collections: r[5],
  color: r[6],
  price: r[7],
  stock: r[8],
  images: JSON.stringify([`/images/${r[9]}.jpg`]),
  featured: r[10],
  description:
    "A sample saree selected to illustrate the Banashree collection. Photography is illustrative; fabric, weave, measurements and pricing require store confirmation before sale.",
  length: "5.5 metres (sample specification)",
  blouse: "0.8 metre unstitched blouse piece (sample specification)",
  care: "Dry clean silk. For cotton and linen, gentle cold wash separately. Confirm the care label of the actual item.",
  fall_pico: i % 3 === 0 ? 15000 : 0,
}));
export const money = (p: number) =>
  new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    minimumFractionDigits: 0,
    maximumFractionDigits: 2,
  }).format(p / 100);
